# 케라스로 만드는 회귀 예제

매사추세츠 보스턴 지역의 주택 가격 예측하기

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/rickiepark/dl-illustrated/blob/master/notebooks/9-3.regression_in_keras.ipynb)

#### 라이브러리를 적재합니다.

In [1]:
import numpy as np
from tensorflow.keras.datasets import boston_housing
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout 
from tensorflow.keras.layers import BatchNormalization 

2026-01-27 15:51:41.731805: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


#### 데이터를 적재합니다.

In [2]:
(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

57026/57026 ━━━━━━━━━━━━━━━━━━━━ 0s 1us/step


In [3]:
X_train.shape

(404, 13)

In [4]:
X_valid.shape

(102, 13)

In [5]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [6]:
y_train[0]

15.2

#### 신경망을 만듭니다.

In [7]:
model = Sequential()

model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())

model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(1, activation='linear'))

/Users/ijaegu/.local/lib/python3.9/site-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [8]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 32)             │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 16)             │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,185 (4.63 KB)

 Trainable params: 1,089 (4.25 KB)

 Non-trainable params: 96 (384.00 B)

#### 모델을 설정합니다.

In [9]:
model.compile(loss='mean_squared_error', optimizer='adam')

#### 훈련!

In [10]:
model.fit(X_train, y_train, 
          batch_size=8, epochs=32, verbose=1, 
          validation_data=(X_valid, y_valid))

Epoch 1/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 6s 25ms/step - loss: 614.3676 - val_loss: 653.5616
Epoch 2/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 597.0190 - val_loss: 605.7876
Epoch 3/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 548.3031 - val_loss: 577.9075
Epoch 4/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 516.3624 - val_loss: 541.6506
Epoch 5/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 524.1331 - val_loss: 510.5238
Epoch 6/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 537.7584 - val_loss: 460.1153
Epoch 7/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 409.8617 - val_loss: 331.6745
Epoch 8/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 456.9783 - val_loss: 293.3017
Epoch 9/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 376.7735 - val_loss: 340.4591
Epoch 10/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 333.1978 - val_loss: 318.9279
Epoch 11/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 327.7334 - val_loss: 254.6623
Epoch 12/32
51/51 ━

In [11]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [ ]:
y_valid[42] 

14.1

In [13]:
model.predict(np.reshape(X_valid[42], [1, 13]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 454ms/step


array([[21.143892]], dtype=float32)